/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingbook.chapter05;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.border.Border;


/**
 *
 * @author Obuhov.Alexey
 */
public class NewJDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public NewJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Integer a = 128; 
        Integer b = 128;
        Integer x = 127;
        Integer y = 127;
        List l = new ArrayList();
        //System.out.println((a==b)  + ";" + (x==y));
        new t11();
        test();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAnswers = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlAnswers.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlAnswers.setName("pnlAnswers"); // NOI18N

        javax.swing.GroupLayout pnlAnswersLayout = new javax.swing.GroupLayout(pnlAnswers);
        pnlAnswers.setLayout(pnlAnswersLayout);
        pnlAnswersLayout.setHorizontalGroup(
            pnlAnswersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        pnlAnswersLayout.setVerticalGroup(
            pnlAnswersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.setName("jToggleButton1"); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAnswers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAnswers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        
        pnlAnswers.removeAll();
        
        test2();
        //getRootPane().repaint();
        //getContentPane().repaint();
        //repaint();
        pack();
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialog dialog = new NewJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
   static class t1 {
        {System.out.println("1");
        }
        static {
            System.out.println("2");
        }
        t1() {
            System.out.println("3");
        }
    }
   
    static class t11 extends t1 {
        {System.out.println("11");
        }
        static {
            System.out.println("12");
        }
        t11() {
            System.out.println("13");
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel pnlAnswers;
    // End of variables declaration//GEN-END:variables
    
    private void test() {
        
        pnlAnswers.setLayout(new BorderLayout());
        
        JPanel pnlAnswersNorth = new JPanel();
        pnlAnswersNorth.setBorder(BorderFactory.createEtchedBorder());
        pnlAnswersNorth.setLayout(new VerticalLayout());
        
        pnlAnswers.add(pnlAnswersNorth, BorderLayout.NORTH);
        
        JPanel pnlAnswer = new JPanel(new VerticalLayout());
        pnlAnswer.setBorder(BorderFactory.createEtchedBorder());
        
        JCheckBox chb1 = new JCheckBox("<html>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla</html>");
        JTextField tf1 = new JTextField();
        
        pnlAnswer.add(chb1);
        pnlAnswer.add(tf1);
        
        pnlAnswersNorth.add(pnlAnswer);
        
        JCheckBox chb2 = new JCheckBox("<html>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla</html>");
        chb2.setBorder(BorderFactory.createEtchedBorder());
        pnlAnswersNorth.add(chb2);
        
        
        JRadioButton radio3 = new JRadioButton("<html>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla</html>");
        JTextField tf3 = new JTextField();
        JRadioButton radio4 = new JRadioButton("<html>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla</html>");
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(radio3);
        bg.add(radio4);
        
        JPanel pnlAnswer3 = new JPanel(new VerticalLayout());
        pnlAnswer3.setBorder(BorderFactory.createEtchedBorder());
        pnlAnswer3.add(radio3);
        pnlAnswer3.add(tf3);
        
        pnlAnswersNorth.add(pnlAnswer3);
        pnlAnswersNorth.add(radio4);
        
    }

    private void test2() {
        
        pnlAnswers.setLayout(new BorderLayout());
        
        JPanel pnlAnswersNorth = new JPanel();
        pnlAnswersNorth.setBorder(BorderFactory.createEtchedBorder());
        pnlAnswersNorth.setLayout(new VerticalLayout());
        
        pnlAnswers.add(pnlAnswersNorth, BorderLayout.NORTH);
        
        JPanel pnlAnswer = new JPanel(new VerticalLayout());
        pnlAnswer.setBorder(BorderFactory.createEtchedBorder());
        
        JCheckBox chb1 = new JCheckBox("<html>answer 1 from question 2</html>");
        JTextField tf1 = new JTextField();
        
        pnlAnswer.add(chb1);
        pnlAnswer.add(tf1);
        
        pnlAnswersNorth.add(pnlAnswer);
        
        JCheckBox chb2 = new JCheckBox("<html>answer 2 from question 2</html>");
        chb2.setBorder(BorderFactory.createEtchedBorder());
        pnlAnswersNorth.add(chb2);
        
        
        JRadioButton radio3 = new JRadioButton("<html>answer 11 from question 2</html>");
        JTextField tf3 = new JTextField();
        JRadioButton radio4 = new JRadioButton("<html>answer 12 from question 2</html>");
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(radio3);
        bg.add(radio4);
        
        JPanel pnlAnswer3 = new JPanel(new VerticalLayout());
        pnlAnswer3.setBorder(BorderFactory.createEtchedBorder());
        pnlAnswer3.add(radio3);
        pnlAnswer3.add(tf3);
        
        pnlAnswersNorth.add(pnlAnswer3);
        pnlAnswersNorth.add(radio4);
        
    }

}



